blog/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name = 'all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('blog/', include('blog.urls'), name = 'blog'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    objects = None
    title = models.CharField(max_length=200, blank = True)
    description = models.TextField()
    data = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    objects = None
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to = "portfolio/images/")
    url = models.URLField(blank = True)
    
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.order_by('-data')
    return render(request, 'blog/all_blogs.html', {'blogs' : blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'base/home.html', {'projects' : projects})

blog/templates/blog/all_blogs.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container text-center">
    <h1 id="blogtitle" class="font-weight-bold text-center">Привет,это мой блог!</h1>
    <p class="text-center mb-5">I was written {{ blogs.count }} blog{{ blogs.count|pluralize }}</p>
</div>
{% load static %}



{% for blog in blogs %}
<div class="row justify-content-center my-3">
    <div class="col-mb-10">
        <a class="nav-link" href="{% url 'blog:detail' blog.id %}"><h1>{{ blog.title }}</h1></a>
        <h6 class="text-muted">{{ blog.data|date:'M d Y' }}</h6>
        <p>{{ blog.description|safe|truncatechars:100 }}</p>
    </div>
</div>

{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'base/base.html' %}
{% block content %}

<h1>{{ blog.title }}</h1>

<div class="row justify-content-center my-3">
    <div class="col-mb-10">
        <h2>{{ blog.data|date:'F jS Y' }}</h2>
    </div>
</div>

<p>{{ blog.description|safe }}</p>

{% endblock %}

portfolio/templates/base/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sumisu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="icon" type="image/jpg" href="{% static 'portfolio/zMAAplkgrU4.jpg' %}">

  </head>

  <body>

  <div class="container">
    <nav class="navbar navbar-expand-lg " style="background-color: #e3e3e3">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'portfolio/zMAAplkgrU4.jpg' %}" width="30" height="30" class="d_infline-block align-top" alt="Sumisu's logo">
        Sumisu
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active " aria-current="page" href="{% url 'home' %}">Домой</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="https://vk.com/id325456943" target="_blank">VK</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="https://www.instagram.com/sumisu05/">INST</a>
          </li>
        </ul>
        <form class="nav-item">
          <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-secondary">Блог</a>
        </form>
      </div>
    </div>
  </nav>
  </div>
<div class="container">
  {% block content %}{% endblock %}
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/base/home.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container text-center">


{% load static %}

<div class="row justify-content-center my-3">
    <div class="col-5">
        <img src="{% static 'portfolio/vMR5HfVuSaE.png' %}" height="460" width="400">
    </div>
</div>

<div class="row justify-content-center mb-3">
    <div class="col-mb-9 text-center">
        <h1 class="font-weight-blod">Sumisu-гений, миллиардер, плэйбой, филантроп, <br>мизантроп и вообще крутой реально.</h1>
    </div>
</div>

</div>

<h2 class="mt-5">Проекты</h2>
<hr>

<div class="row">
    {% for project in projects %}

    <div class="col-lg-4 col-mb-6">
        {% if project.url %}
            <a href="{{ project.url }}">
                <img src="{{ project.image.url }}" height="200" width="300">
            </a>
        {% else %}
        <img src="{{ project.image.url }}">
        {% endif %}

        <h2>{{ project.title }}</h2>
        <p>{{ project.description }}</p>

    </div>
    {% endfor %}
</div>

{% endblock %}